version: "3"
services:
    web:
      image: wordpress
      links:
        - mysql:mysql1
      environment:
        - WORDPRESS_DB_PASSWORD=sample
        - WORDPRESS_DB_HOST=mysql1
      ports:
        - "8080:80"
    mysql:
      image: mysql:latest
      environment:
        - MYSQL_ROOT_PASSWORD=sample
        - MYSQL_DATABASE=wordpress